# Generated by Django 6.0.3 on 2026-03-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('placas', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
